fix: make ts recognize typedefs
Fixes `error TS7016: Could not find a declaration file for module X implicitly has an 'any' type. There are types at X, but this result could not be resolved when respecting package.json "exports". The X library may need to update its package.json or typings.`